service: dynamodb-tables

provider:
  name: aws
  runtime: nodejs18.x # Or any other runtime, this is just a placeholder as we are only defining resources
  iam:
    role: arn:aws:iam::367311722984:role/LabRole0
  region: us-east-1 # Specify your desired region
  stage: dev  # valor por defecto si no se indica en línea de comandos

custom:
  tablePrefix: ${self:provider.stage}
  
resources:
  Resources:
    PersonasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: $t_{self:custom.tablePrefix}_user
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    AccessTokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: $t_{self:custom.tablePrefix}_accessTokens
        AttributeDefinitions:
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: token
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    CursosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: $t_{self:custom.tablePrefix}_cursos
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: curso_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: curso_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    ProdComprasTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: $t_{self:custom.tablePrefix}_compras
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: order_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: order_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
